version: '3'
services:
  php:
    build:
      context: config/php
      args:
        PUID: $PUID
        PGID: $PGID
    volumes:
      - ../:/var/www
    environment:
#      XDEBUG_CONFIG: "client_host=host.docker.internal" #for Windows/Mac
      XDEBUG_CONFIG: "client_host=192.168.227.1"
      PHP_IDE_CONFIG: serverName=Docker
    depends_on:
      - mysql
    links:
      - mysql:db
    networks:
      - internal
  nginx:
    build:
      context: config/nginx
      args:
        PUID: $PUID
        PGID: $PGID
    volumes:
      - ../:/var/www
    ports:
      - 80:80
    depends_on:
      - php
    networks:
      - internal
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dating
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - internal
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.227.0/28
